// ── Eduzah Real Data ─────────────────────────────────────

export const SITE = {
  name: "Eduzah",
  tagline: "Eduzah شركة سوفتوير متخصصة في تقديم التدريبات التقنية في مجالات تطوير البرمجيات والذكاء الاصطناعي",
  tagline_en: "Eduzah — A software company specialized in technical training in software development and AI",
  about: "Eduzah أكاديمية التدريب المهني الرائدة في مصر. منذ تأسيسنا دربنا أكثر من 5000 محترف في مجالات التكنولوجيا، إدارة الموارد البشرية، اللغات، وتدريب الأطفال.",
  phone: "+201044222881",
  email: "info@eduzah.com",
  location: "سوهاج، مصر",
  hours: "السبت – الخميس: 10 صباحاً – 6 مساءً",
  vodafoneCash: "01044222881",
  social: {
    facebook: "https://www.facebook.com/Eduzah.egy",
    linkedin: "https://www.linkedin.com/company/eduzah",
    instagram: "https://www.instagram.com/eduzah.egy/",
  },
};

// ── TRACKS ─────────────────────────────────────────────
export const TRACKS = [
  {
    id: "technology",
    title_ar: "تكنولوجيا",
    title_en: "Technology",
    icon: "TK",
    color: "#d91b5b",
    desc_ar: "برامج شاملة في تطوير الويب، الموبايل، الذكاء الاصطناعي، والأمن السيبراني",
    desc_en: "Comprehensive programs in web development, mobile, AI, and cybersecurity",
    subtracks: [
      { id: "programming-fundamentals", title_ar: "أساسيات البرمجة", title_en: "Programming Fundamentals" },
      { id: "frontend", title_ar: "تطوير الواجهة الأمامية", title_en: "Frontend Development" },
      { id: "backend", title_ar: "تطوير الواجهة الخلفية", title_en: "Backend Development" },
      { id: "flutter", title_ar: "تطوير تطبيقات Flutter", title_en: "Flutter Development" },
      { id: "data-analysis", title_ar: "تحليل البيانات", title_en: "Data Analysis" },
      { id: "cybersecurity", title_ar: "الأمن السيبراني", title_en: "Cybersecurity" },
      { id: "ai-ml", title_ar: "الذكاء الاصطناعي", title_en: "AI & Machine Learning" },
      { id: "ui-ux", title_ar: "UI/UX Design", title_en: "UI/UX Design" },
    ],
  },
  {
    id: "management",
    title_ar: "إدارة",
    title_en: "Management",
    icon: "MG",
    color: "#10b981",
    desc_ar: "برامج في الموارد البشرية، التصميم التعليمي، والمهارات الوظيفية",
    desc_en: "Programs in HR, instructional design, and professional skills",
    subtracks: [
      { id: "hr", title_ar: "الموارد البشرية", title_en: "Human Resources" },
      { id: "instructional-design", title_ar: "التصميم التعليمي", title_en: "Instructional Design" },
      { id: "soft-skills", title_ar: "المهارات الناعمة", title_en: "Soft Skills" },
    ],
  },
  {
    id: "english",
    title_ar: "اللغة الإنجليزية",
    title_en: "English Language",
    icon: "EN",
    color: "#faa633",
    desc_ar: "من المستوى الأساسي حتى المتقدم مع برامج متخصصة",
    desc_en: "From basic to advanced with specialized business English",
    subtracks: [
      { id: "english-basics", title_ar: "الأساسيات", title_en: "Basics" },
      { id: "english-levels", title_ar: "المستويات A1 – C2", title_en: "Levels A1 – C2" },
      { id: "english-business", title_ar: "الإنجليزية المتخصصة", title_en: "Specialized English" },
    ],
  },
  {
    id: "children",
    title_ar: "تدريب الأطفال",
    title_en: "Children Programs",
    icon: "KD",
    color: "#8b5cf6",
    desc_ar: "برامج مخصصة للأطفال في البرمجة واللغة الإنجليزية بأساليب مبتكرة",
    desc_en: "Dedicated programs for children in coding and English with innovative methods",
    subtracks: [
      { id: "coding-kids", title_ar: "برمجة للأطفال", title_en: "Coding for Kids" },
      { id: "english-kids", title_ar: "إنجليزية للأطفال", title_en: "English for Kids" },
      { id: "annual-track", title_ar: "المسار السنوي (2 ترمات)", title_en: "Annual Track (2 Terms)" },
    ],
  },
];

// ── TRAINERS ───────────────────────────────────────────
export const TRAINERS = [
  {
    id: "t1",
    name: "م. خالد حسن",
    name_en: "Eng. Khaled Hassan",
    username: "khalid@eduzah.com",
    password: "trainer123",
    specialty_ar: "تطوير الويب والـ AI",
    specialty_en: "Web Dev & AI",
    bio_ar: "مطور Full Stack بخبرة +8 سنوات. خبير في React, Node.js, وأدوات AI الحديثة.",
    bio_en: "Full Stack Developer with 8+ years. Expert in React, Node.js, and AI tools.",
    avatar: "خ",
    courses: ["front-end", "ai-ml"],
    image: null,
  },
  {
    id: "t2",
    name: "م. منى أحمد",
    name_en: "Eng. Mona Ahmed",
    username: "mona@eduzah.com",
    password: "trainer123",
    specialty_ar: "تصميم وتطوير الموبايل",
    specialty_en: "Design & Mobile Dev",
    bio_ar: "مصممة UI/UX ومطورة Flutter بخبرة +5 سنوات. متخصصة في تجربة المستخدم.",
    bio_en: "UI/UX Designer and Flutter developer with 5+ years specializing in UX.",
    avatar: "م",
    courses: ["mobile-dev", "ui-ux"],
    image: null,
  },
];

// ── COURSES ────────────────────────────────────────────
export const COURSES = [
  {
    id: "front-end",
    slug: "front-end",
    title: "Front-End Web Development",
    title_en: "Front-End Web Development",
    trackId: "technology",
    subtracks: ["frontend"],
    cat: "tech",
    icon: null,
    color: "#d91b5b",
    image: null,
    price: 8500,
    installment: 2850,
    trainingTypes: ["online", "offline"],
    duration: "20 أسبوع",
    hours: 160,
    projects: 15,
    rating: 4.9,
    students: 500,
    featured: true,
    badge: "الأكثر طلباً",
    badge_en: "Most requested",
    tagline: "دبلومة Front-End Web Development مدمجة بالذكاء الاصطناعي",
    tagline_en: "Front-End Web Development Diploma with AI Integration",
    desc: "تعلّم بناء مواقع وتطبيقات ويب احترافية من الصفر حتى الاحتراف. منهج متكامل من HTML وCSS لحد React مع أدوات AI.",
    desc_en: "Learn to build professional websites and web apps from scratch to advanced. A complete curriculum from HTML & CSS to React with AI tools.",
    bullets: [
      "مدمج بأدوات AI للمطورين",
      "15+ مشروع حقيقي على CV",
      "دعم توظيف مع أكبر شركات مصر",
      "شهادة معتمدة عند الإتمام",
    ],
    bullets_en: [
      "Integrated with AI tools for developers",
      "15+ real projects for your CV",
      "Hiring support with top companies in Egypt",
      "Accredited certificate upon completion",
    ],
    outcomes: [
      "بناء مواقع احترافية من الصفر",
      "كتابة كود نظيف بـ TypeScript",
      "React وNext.js في مشاريع حقيقية",
      "التعامل مع REST APIs",
      "استخدام AI لمضاعفة الإنتاجية",
      "Portfolio جاهز بـ 15+ مشروع",
    ],
    outcomes_en: [
      "Build professional websites from scratch",
      "Write clean code with TypeScript",
      "React & Next.js in real projects",
      "Work with REST APIs",
      "Use AI to boost productivity",
      "Portfolio with 15+ projects",
    ],
    techStack: [
      { label: "الأساسيات", items: ["HTML5","CSS3","SASS/SCSS","Bootstrap 5","Tailwind CSS","Git & GitHub"] },
      { label: "JavaScript", items: ["ES6+ Modern JS","TypeScript","DOM & BOM","Async/Await","APIs & Fetch","OOP"] },
      { label: "React Framework", items: ["React.js","React Hooks","Redux Toolkit","React Router","Next.js","React Query"] },
      { label: "AI Tools", items: ["GitHub Copilot","ChatGPT للكود","Cursor AI","Prompt Engineering","v0 by Vercel"], ai: true },
    ],
    curriculum: [
      { title: "HTML5 & CSS3 Fundamentals", lessons: ["HTML5 Semantic Elements","CSS3 & Flexbox & Grid","Responsive Web Design","مشروع: موقع شخصي"] },
      { title: "SASS & Bootstrap & Tailwind", lessons: ["SASS Variables & Mixins","Bootstrap 5 Grid","Tailwind Utility Classes","مشروع: Dashboard"] },
      { title: "JavaScript ES6+", lessons: ["Variables, Functions, Scope","DOM Manipulation","ES6+ Features","مشروع: App تفاعلي"] },
      { title: "Async JS & APIs", lessons: ["Promises & Async/Await","Fetch API & Axios","مشروع: Movies App"] },
      { title: "TypeScript", lessons: ["Types & Interfaces","Generics","TypeScript with React"] },
      { title: "React.js & Next.js", lessons: ["Components & Hooks","Redux Toolkit","Next.js SSR","مشروع نهائي: E-commerce"] },
      { title: "AI Tools للمطورين", lessons: ["GitHub Copilot","Prompt Engineering","Cursor AI"] },
    ],
    reviews: [
      { name:"أحمد محمد", role:"Frontend Dev @ Vodafone", text:"الدبلومة غيّرت مسيرتي. في 6 شهور بقيت Frontend Developer.", avatar:"أ", rating:5 },
      { name:"محمد علي", role:"Junior React Developer", text:"كنت مش عارف حاجة. دلوقتي React Developer وعندي Portfolio.", avatar:"م", rating:5 },
      { name:"سارة أحمد", role:"UI Developer @ Swvl", text:"أفضل استثمار عملته. جزء الـ AI Tools بيفرق فعلاً.", avatar:"س", rating:5 },
    ],
    instructorId: "t1",
    presentationUrl: null,
  },
  {
    id: "ai-ml",
    slug: "ai-ml",
    title: "AI & Machine Learning",
    title_en: "AI & Machine Learning",
    trackId: "technology",
    subtracks: ["ai-ml"],
    cat: "tech",
    icon: null,
    color: "#672d86",
    image: null,
    price: 12000,
    installment: 4000,
    trainingTypes: ["online", "offline"],
    duration: "17 أسبوع",
    hours: 120,
    projects: 7,
    rating: 4.8,
    students: 320,
    featured: true,
    badge: "الأكثر طلباً",
    badge_en: "Most requested",
    tagline: "دبلومة AI & Machine Learning",
    tagline_en: "AI & Machine Learning Diploma",
    desc: "إتقان أساسيات الذكاء الاصطناعي وبناء نماذج ML حقيقية بـ Python.",
    desc_en: "Master AI fundamentals and build real ML models with Python.",
    bullets: ["Python for AI","Machine Learning","Deep Learning","Real Projects"],
    outcomes: ["Python للـ AI","ML Models حقيقية","Deep Learning","NLP Basics","AI Portfolio"],
    techStack: [
      { label: "Python", items: ["Python 3","NumPy","Pandas","Matplotlib"] },
      { label: "Machine Learning", items: ["Scikit-learn","Supervised Learning","Unsupervised Learning"] },
      { label: "Deep Learning", items: ["TensorFlow","Keras","Neural Networks","CNNs"] },
    ],
    curriculum: [
      { title: "Python Fundamentals", lessons: ["Python 3 Basics","Data Structures","Functions & OOP"] },
      { title: "Data Analysis", lessons: ["NumPy & Pandas","Data Visualization","EDA"] },
      { title: "Machine Learning", lessons: ["Supervised Learning","Unsupervised Learning","Model Evaluation"] },
      { title: "Deep Learning", lessons: ["Neural Networks","CNNs","Transfer Learning","Project: Final AI Project"] },
    ],
    reviews: [
      { name:"جمال فتحي", role:"Data Scientist", text:"محتوى رائع ومشاريع حقيقية. تم توظيفي بعد 3 شهور.", avatar:"ج", rating:5 },
    ],
    instructorId: "t1",
    presentationUrl: null,
  },
  {
    id: "mobile-dev",
    slug: "mobile-dev",
    title: "Mobile App Development",
    title_en: "Mobile App Development (Flutter)",
    trackId: "technology",
    subtracks: ["flutter"],
    cat: "tech",
    icon: null,
    color: "#4a1f6e",
    image: null,
    price: 10000,
    installment: 3400,
    trainingTypes: ["online", "offline"],
    duration: "16 أسبوع",
    hours: 120,
    projects: 6,
    rating: 4.7,
    students: 280,
    featured: true,
    badge: null,
    tagline: "دبلومة Mobile App Development بـ Flutter",
    tagline_en: "Mobile App Development Diploma with Flutter",
    desc: "بناء تطبيقات iOS و Android احترافية باستخدام Flutter.",
    desc_en: "Build cross-platform iOS & Android apps using Flutter.",
    bullets: ["Flutter & Dart","State Management","REST APIs","App Publishing"],
    outcomes: ["Flutter apps","Dart language","Firebase integration","App Store publishing"],
    techStack: [
      { label: "Dart & Flutter", items: ["Dart Language","Flutter Widgets","Layouts","Navigation"] },
      { label: "State Management", items: ["Provider","Riverpod","BLoC Pattern"] },
      { label: "Backend Integration", items: ["REST APIs","Firebase","Local Storage"] },
    ],
    curriculum: [
      { title: "Dart Basics", lessons: ["Variables & Functions","OOP in Dart","Async Programming"] },
      { title: "Flutter UI", lessons: ["Widgets","Layouts","Responsive Design"] },
      { title: "State & APIs", lessons: ["State Management","HTTP & APIs","Firebase"] },
      { title: "Publishing", lessons: ["App Store","Google Play","Project: Final App"] },
    ],
    reviews: [
      { name:"نور الدين", role:"Flutter Developer", text:"شرح ممتاز وتطبيق عملي على كل درس.", avatar:"ن", rating:5 },
    ],
    instructorId: "t2",
    presentationUrl: null,
  },
  {
    id: "ui-ux",
    slug: "ui-ux",
    title: "UI/UX Design",
    title_en: "UI/UX Design",
    trackId: "technology",
    subtracks: ["ui-ux"],
    cat: "tech",
    icon: null,
    color: "#faa633",
    image: null,
    price: 7500,
    installment: 2500,
    trainingTypes: ["online", "offline"],
    duration: "12 أسبوع",
    hours: 80,
    projects: 5,
    rating: 4.8,
    students: 200,
    featured: false,
    badge: null,
    tagline: "دبلومة UI/UX Design",
    tagline_en: "UI/UX Design Diploma",
    desc: "تصميم واجهات مستخدم احترافية باستخدام Figma.",
    desc_en: "Design stunning user interfaces with Figma and Adobe XD.",
    bullets: ["Figma","User Research","Wireframing","Portfolio"],
    outcomes: ["Figma mastery","UX Research","Design Systems","Portfolio"],
    techStack: [
      { label: "Design Tools", items: ["Figma","Adobe XD","Photoshop Basics"] },
      { label: "UX Process", items: ["User Research","Wireframing","Prototyping","Usability Testing"] },
    ],
    curriculum: [
      { title: "Design Fundamentals", lessons: ["Color Theory","Typography","Grid Systems"] },
      { title: "Figma", lessons: ["Components","Auto Layout","Prototyping"] },
      { title: "UX Process", lessons: ["User Research","Wireframes","User Testing","Project: Portfolio Project"] },
    ],
    reviews: [],
    instructorId: "t2",
    presentationUrl: null,
  },
  {
    id: "hr-management",
    slug: "hr-management",
    title: "HR Management",
    title_en: "HR Management",
    trackId: "management",
    subtracks: ["hr"],
    cat: "hr",
    icon: null,
    color: "#10b981",
    image: null,
    price: 6000,
    installment: 2000,
    trainingTypes: ["online", "offline"],
    duration: "12 أسبوع",
    hours: 80,
    projects: 3,
    rating: 4.9,
    students: 150,
    featured: false,
    badge: null,
    tagline: "دبلومة HR Management",
    tagline_en: "HR Management Diploma",
    desc: "إدارة الموارد البشرية الشاملة تشمل التوظيف والأداء وقانون العمل.",
    desc_en: "Comprehensive HR management including recruitment, performance, and labor law.",
    bullets: ["Recruitment","Performance Mgmt","Labor Law","HR Analytics"],
    outcomes: ["Recruitment skills","Performance management","Labor law knowledge","HR Analytics"],
    techStack: [
      { label: "HR Fundamentals", items: ["Recruitment & Selection","Training & Development","Performance Management"] },
      { label: "HR Tools", items: ["Labor Law","Compensation","HR Analytics","HRIS"] },
    ],
    curriculum: [
      { title: "HR Fundamentals", lessons: ["Intro to HRM","Organizational Structure"] },
      { title: "Recruitment", lessons: ["Sourcing","Interviewing","Onboarding"] },
      { title: "Performance & Law", lessons: ["KPIs","Labor Law Egypt","Compensation","Project: Capstone Project"] },
    ],
    reviews: [
      { name:"ولاء أشرف", role:"HR Specialist", text:"كورس ممتاز لكل المبتدئين في HR.", avatar:"و", rating:5 },
    ],
    instructorId: null,
    presentationUrl: null,
  },
  {
    id: "soft-skills",
    slug: "soft-skills",
    title: "Soft Skills & Communication",
    title_en: "Soft Skills & Communication",
    trackId: "management",
    subtracks: ["soft-skills"],
    cat: "hr",
    icon: null,
    color: "#0ea5e9",
    image: null,
    price: 4500,
    installment: 1500,
    trainingTypes: ["online", "offline"],
    duration: "8 أسابيع",
    hours: 48,
    projects: 2,
    rating: 4.7,
    students: 180,
    featured: false,
    badge: null,
    tagline: "تطوير المهارات الشخصية والتواصل الفعّال",
    tagline_en: "Develop Soft Skills & Effective Communication",
    desc: "برنامج شامل لتطوير مهارات التواصل، القيادة، وإدارة الوقت.",
    desc_en: "Comprehensive program for communication, leadership, and time management skills.",
    bullets: ["Communication Skills","Leadership","Teamwork","Time Management"],
    outcomes: ["Public Speaking","Team Leadership","Conflict Resolution","Presentation Skills"],
    techStack: [],
    curriculum: [
      { title: "Communication Skills", lessons: ["Verbal & Non-verbal","Active Listening","Presentation Skills"] },
      { title: "Leadership & Teamwork", lessons: ["Leadership Styles","Team Dynamics","Conflict Resolution"] },
      { title: "Professional Development", lessons: ["Time Management","Goal Setting","Project: Capstone Presentation"] },
    ],
    reviews: [],
    instructorId: null,
    presentationUrl: null,
  },
  {
    id: "english-basics",
    slug: "english-basics",
    title: "English Language – A1 to B2",
    title_en: "English Language – A1 to B2",
    trackId: "english",
    subtracks: ["english-levels"],
    cat: "english",
    icon: null,
    color: "#faa633",
    image: null,
    price: 5000,
    installment: 1700,
    trainingTypes: ["online", "offline"],
    duration: "16 أسبوع",
    hours: 96,
    projects: 0,
    rating: 4.8,
    students: 220,
    featured: false,
    badge: null,
    tagline: "رحلة تعلم اللغة الإنجليزية من الصفر حتى B2",
    tagline_en: "English learning journey from zero to B2",
    desc: "برنامج متكامل لتعلم اللغة الإنجليزية من المستوى الأساسي A1 حتى B2.",
    desc_en: "Complete English program from beginner A1 to intermediate B2.",
    bullets: ["Grammar","Vocabulary","Speaking","Writing"],
    outcomes: ["Fluent Communication","Grammar Mastery","Business Email Writing","Interview English"],
    techStack: [],
    curriculum: [
      { title: "A1 – Beginner", lessons: ["Introductions","Numbers & Dates","Basic Grammar"] },
      { title: "A2 – Elementary", lessons: ["Daily Routines","Simple Tenses","Vocabulary Building"] },
      { title: "B1 – Intermediate", lessons: ["Reading Comprehension","Writing Paragraphs","Conversation"] },
      { title: "B2 – Upper Intermediate", lessons: ["Advanced Grammar","Essay Writing","Speaking Fluency","Certificate Test"] },
    ],
    reviews: [],
    instructorId: null,
    presentationUrl: null,
  },
  {
    id: "coding-kids",
    slug: "coding-kids",
    title: "برمجة للأطفال",
    title_en: "Coding for Kids",
    trackId: "children",
    subtracks: ["coding-kids"],
    cat: "children",
    icon: null,
    color: "#8b5cf6",
    image: null,
    price: 3500,
    installment: 1200,
    trainingTypes: ["online", "offline"],
    duration: "ترمين سنوياً",
    hours: 60,
    projects: 5,
    rating: 5.0,
    students: 90,
    featured: false,
    badge: "للأطفال",
    badge_en: "For children",
    tagline: "تعليم البرمجة للأطفال بطريقة ممتعة وتفاعلية",
    tagline_en: "Teach kids coding in a fun and interactive way",
    desc: "برنامج سنوي (ترمين) لتعليم الأطفال البرمجة باستخدام Scratch وأدوات مبتكرة.",
    desc_en: "Annual program (2 terms) teaching children coding using Scratch and innovative tools.",
    bullets: ["Scratch Programming","Game Design","Problem Solving","Creative Thinking"],
    outcomes: ["Basic Coding Concepts","Game Building","Logical Thinking","Creativity"],
    techStack: [],
    curriculum: [
      { title: "الترم الأول", lessons: ["مقدمة للبرمجة","Scratch Basics","بناء لعبة بسيطة","مشروع إبداعي"] },
      { title: "الترم الثاني", lessons: ["Scratch Advanced","Micro:bit Intro","مشروع نهائي"] },
    ],
    reviews: [],
    instructorId: null,
    presentationUrl: null,
  },
];

// ── NEWS ──────────────────────────────────────────────
export const NEWS = [
  {
    id: 1,
    title: "Eduzah تطلق 10 كورسات جديدة في مجال الـ AI!",
    title_en: "Eduzah Launches 10 New AI Courses!",
    dateIso: "2025-03-24",
    date: "24 مارس 2025",
    tag: "إعلان",
    tag_en: "Announcement",
    images: ["/images/team-office.webp"],
    excerpt: "في إطار خطتها التوسعية، أعلنت Eduzah عن إطلاق 10 كورسات جديدة في الذكاء الاصطناعي ستبدأ الدفعة الجديدة في أبريل 2025.",
    excerpt_en: "As part of its expansion plan, Eduzah announced the launch of 10 new AI courses. The new batch will begin in April 2025.",
    featured: true,
  },
  {
    id: 2,
    title: "Eduzah تفوز بجائزة أفضل منصة تعليمية 2025",
    title_en: "Eduzah Wins Best Educational Platform 2025",
    dateIso: "2025-03-20",
    date: "20 مارس 2025",
    tag: "إنجاز",
    tag_en: "Achievement",
    images: ["/images/team-banner.webp"],
    excerpt: "حصلت Eduzah على جائزة أفضل منصة تعليمية عربية لعام 2025 تقديراً لجهودها في رفع مستوى التدريب المهني.",
    excerpt_en: "Eduzah received the Best Arabic Educational Platform Award for 2025 in recognition of its efforts to elevate professional training standards.",
    featured: false,
  },
  {
    id: 3,
    title: "شراكة استراتيجية مع أكبر شركات التوظيف",
    title_en: "Strategic Partnership with Top Recruitment Companies",
    dateIso: "2025-03-15",
    date: "15 مارس 2025",
    tag: "شراكة",
    tag_en: "Partnership",
    images: [],
    excerpt: "وقّعت Eduzah شراكة مع 5 شركات توظيف كبرى لضمان توظيف خريجينا في أفضل الشركات المصرية.",
    excerpt_en: "Eduzah signed a partnership with 5 major recruitment companies to ensure employment opportunities for our graduates at Egypt's top firms.",
    featured: false,
  },
];

// ── EXAMS ────────────────────────────────────────────
export const EXAMS = [
  { id:1, title:"امتحان HTML & CSS", courseId:"front-end", type:"mcq", dueDate:"2025-03-28", duration:45, lessonIndex:null, questions:[{q:"ما هو الـ tag لإنشاء رابط؟",opts:["<link>","<a>","<href>","<url>"],ans:1},{q:"CSS property للون الخلفية؟",opts:["color","background-color","bg","fill"],ans:1},{q:"ناتج 2+'2' في JS؟",opts:["4","22","NaN","Error"],ans:1}], submissions:[] },
  { id:2, title:"تاسك: Landing Page", courseId:"front-end", type:"task", dueDate:"2025-04-05", description:"ابني Landing Page كاملة باستخدام HTML & CSS.", lessonIndex:null, questions:[], submissions:[] },
  { id:3, title:"امتحان Python Basics", courseId:"ai-ml", type:"mcq", dueDate:"2025-04-10", duration:60, lessonIndex:null, questions:[{q:"كيف تطبع 'Hello' في Python؟",opts:["echo","print('Hello')","console.log","cout"],ans:1}], submissions:[] },
];

// ── PROGRAMS (Key Programs Section) ──────────────────
export const PROGRAMS = [
  {
    id: "prog-1",
    title_ar: "تطوير تطبيقات الويب",
    title_en: "Web Application Development",
    desc_ar: "برنامج شامل لتطوير المواقع والتطبيقات الاحترافية من HTML وCSS حتى React والـ AI.",
    desc_en: "Comprehensive program for professional web development from HTML & CSS to React and AI tools.",
    image: "/images/team-office.webp",
    featured: true,
  },
  {
    id: "prog-2",
    title_ar: "الذكاء الاصطناعي وتحليل البيانات",
    title_en: "AI & Data Analysis",
    desc_ar: "تعلم أساسيات الذكاء الاصطناعي وبناء نماذج Machine Learning حقيقية بـ Python.",
    desc_en: "Learn AI fundamentals and build real Machine Learning models with Python.",
    image: null,
    featured: true,
  },
  {
    id: "prog-3",
    title_ar: "إدارة الموارد البشرية",
    title_en: "Human Resources Management",
    desc_ar: "دبلومة HR متكاملة تشمل التوظيف وإدارة الأداء وقانون العمل المصري.",
    desc_en: "Complete HR diploma covering recruitment, performance management, and Egyptian labor law.",
    image: null,
    featured: true,
  },
  {
    id: "prog-4",
    title_ar: "برامج الأطفال",
    title_en: "Children Programs",
    desc_ar: "برامج تفاعلية لتعليم الأطفال البرمجة واللغة الإنجليزية بأساليب ممتعة.",
    desc_en: "Interactive programs teaching children coding and English in fun, engaging ways.",
    image: "/images/team-banner.webp",
    featured: false,
  },
];

// ── TESTIMONIALS ──────────────────────────────────────
export const TESTIMONIALS = [
  {
    id: "t1",
    name: "أحمد محمد",
    name_en: "Ahmed Mohamed",
    course_ar: "دبلومة Front-End",
    course_en: "Front-End Diploma",
    comment_ar: "Eduzah غيّرت مسيرتي المهنية. في 6 شهور بقيت Frontend Developer براتب ضعف اللي كنت فيه.",
    comment_en: "Eduzah transformed my career. In 6 months I became a Frontend Developer with double my previous salary.",
    rating: 5,
    image: null,
    avatar: "أ",
  },
  {
    id: "t2",
    name: "سلمى باسل",
    name_en: "Salma Basel",
    course_ar: "دبلومة HR",
    course_en: "HR Diploma",
    comment_ar: "المتابعة المستمرة وأسلوب المدربين كان على أعلى مستوى. استثمار يستحق.",
    comment_en: "Continuous support and trainer quality were top-notch. Truly a worthwhile investment.",
    rating: 5,
    image: null,
    avatar: "س",
  },
  {
    id: "t3",
    name: "جمال فتحي",
    name_en: "Gamal Fathy",
    course_ar: "دبلومة AI",
    course_en: "AI Diploma",
    comment_ar: "التطبيق العملي ساعدني على الفهم العميق. حصلت على وظيفة Data Scientist بعد 3 شهور.",
    comment_en: "Hands-on practice gave me deep understanding. Got a Data Scientist job after 3 months.",
    rating: 5,
    image: null,
    avatar: "ج",
  },
  {
    id: "t4",
    name: "نور الدين",
    name_en: "Nour Eldeen",
    course_ar: "Flutter Development",
    course_en: "Flutter Development",
    comment_ar: "شرح ممتاز وتطبيق عملي على كل درس. أنصح بـ Eduzah لكل من يريد الاحتراف.",
    comment_en: "Excellent explanations with practical application in every lesson. I recommend Eduzah for anyone who wants to excel.",
    rating: 5,
    image: null,
    avatar: "ن",
  },
];

// ── TEAM MEMBERS ─────────────────────────────────────
export const TEAM_MEMBERS = [
  {
    id: "tm-1",
    name: "محمد عمر",
    name_en: "Mohamed Omar",
    role_ar: "المدير التنفيذي",
    role_en: "CEO & Founder",
    bio_ar: "مؤسس Eduzah وخبير في مجال التدريب المهني مع خبرة تزيد عن 10 سنوات في تطوير الكفاءات البشرية.",
    bio_en: "Founder of Eduzah and expert in professional training with over 10 years of experience in human capital development.",
    email: "ceo@eduzah.com",
    linkedin: "https://www.linkedin.com/company/eduzah",
    image: null,
    avatar: "م",
    order: 1,
  },
  {
    id: "tm-2",
    name: "سارة حسن",
    name_en: "Sara Hassan",
    role_ar: "مديرة العمليات",
    role_en: "Operations Manager",
    bio_ar: "مسؤولة عن تطوير مناهج التدريب وضمان جودة البرامج التعليمية في Eduzah.",
    bio_en: "Responsible for curriculum development and ensuring quality of educational programs at Eduzah.",
    email: "ops@eduzah.com",
    linkedin: "https://www.linkedin.com/company/eduzah",
    image: null,
    avatar: "س",
    order: 2,
  },
];

// ── INIT USERS ────────────────────────────────────────
export const INIT_USERS = [
  { id:"admin-1", name:"Admin Eduzah", email:"admin@eduzah.com", password:"admin123", role:"admin", status:"approved", avatar:"A", enrolledCourses:[] },
  { id:"s1", name:"أحمد محمد", email:"ahmed@test.com", password:"123456", role:"student", status:"approved", avatar:"أ", enrolledCourses:[{courseId:"front-end",progress:65,completedLessons:[0,1,2,3]},{courseId:"ai-ml",progress:30,completedLessons:[0,1]}] },
  { id:"s2", name:"سارة علي", email:"sara@test.com", password:"123456", role:"student", status:"pending", avatar:"س", enrolledCourses:[] },
  { id:"i1", name:"م. خالد حسن", email:"khalid@test.com", password:"123456", role:"instructor", status:"approved", avatar:"خ", enrolledCourses:[], assignedCourses:["front-end","ai-ml"] },
  { id:"i2", name:"م. منى أحمد", email:"mona@test.com", password:"123456", role:"instructor", status:"approved", avatar:"م", enrolledCourses:[], assignedCourses:["mobile-dev","ui-ux"] },
];
